name: Build/upload docs and trigger ReadTheDocs building

on:
  push:
    branches:
      - master
  pull_request: {}
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install
      run: |
        python -m pip install -U pip
        pip install --progress-bar off -U .[document]
    - name: Build
      run: |
        cd docs
        make html
      env:
        OMP_NUM_THREADS: 1

    - uses: actions/upload-artifact@v2
      with:
        name: artifacts-${{ github.sha }}
        path: docs/source/tutorial

    - name: curl
      run: |
        curl ${{ secrets.RTDS_WEBHOOK_URL }} \
        -X POST \
        -d 'token=${{ secrets.RTDS_WEBHOOK_URL }}' \
        -d 'branches=$(git branch --show-current)'
