name: Build/upload docs

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install
      run: |
        python -m pip install -U pip
        pip install --progress-bar off -U .[document]
    - name: Build
      run: |
        cd docs
        make html
      env:
        OMP_NUM_THREADS: 1

    - uses: actions/upload-artifact@v2
      with:
        name: artifacts-${{ github.sha }}
        path: docs/source/tutorial

    - uses: dfm/rtds-action@v1
      with:
        webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
        webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
        commit_ref: ${{ github.ref }}
